### ISSUE TITLE
The header content contains invalid characters

### ISSUE THREAD

**Issue by nacimgoura** [simplecrawler/simplecrawler#399]
Hello,
I use the last version of simplecrawler.
When crawling a site my program stops and displays this error : 
```
_http_outgoing.js:492
    throw new TypeError('The header content contains invalid characters');
 ^

TypeError: The header content contains invalid characters
at validateHeader (_http_outgoing.js:492:11)
at ClientRequest.setHeader (_http_outgoing.js:496:3)
at new ClientRequest (_http_client.js:171:14)
at Object.request (http.js:39:10)
at /home/ngoura/Documents/projet/nacim/node_modules/simplecrawler/lib/crawler.js:1185:36
at FetchQueue.update (/home/ngoura/Documents/projet/nacim/node_modules/simplecrawler/lib/queue.js:229:9)
at Crawler.fetchQueueItem (/home/ngoura/Documents/projet/nacim/node_modules/simplecrawler/lib/crawler.js:1163:19)
at /home/ngoura/Documents/projet/nacim/node_modules/simplecrawler/lib/crawler.js:1786:25
at FetchQueue.oldestUnfetchedItem (/home/ngoura/Documents/projet/nacim/node_modules/simplecrawler/lib/queue.js:250:13)
at Crawler.crawl (/home/ngoura/Documents/projet/nacim/node_modules/simplecrawler/lib/crawler.js:1738:19)
at ontimeout (timers.js:469:11)
at tryOnTimeout (timers.js:304:5)
at Timer.listOnTimeout (timers.js:264:5)
```
I put in a try catch but the program still stops, so I can't crawl my site :disappointed:

**Comment by nacimgoura** [comment]
No resolution ?

**Comment by konstantinblaesi** [comment]
@nacimgoura Which page is that? We need a way to reproduce the issue and write a proper test case for it. Looks like the server is sending HTTP headers in a bad format?

**Comment by nacimgoura** [comment]
Hello,
thank you for your response.
I have the bug with these page: 
- http://www.hautesavoie.fr/recherche?page=21&search_api_views_fulltext=Haute-savoie&type=All
- http://www.hautesavoie.fr/recherche?page=16&search_api_views_fulltext=Haute-savoie&type=All
- http://www.hautesavoie.fr/recherche?page=15&search_api_views_fulltext=Haute-savoie&type=All
- http://www.hautesavoie.fr/recherche?page=18&search_api_views_fulltext=Haute-savoie&type=All

**Comment by rodrigogs** [comment]
Same here. My suggestion is to create a numeric hash from the url, so this problem will never happen.

**Comment by braj1999** [comment]
Hello,
I am facing the same issue.Is there any work around as the crawling is stopped in my case with the same error.

**Comment by mattlanham** [comment]
Yea same - crawler stops when it hits that

**Comment by upugo-dev** [comment]
I have also experienced this issue running simplecrawler 1.1.6 on https://www.wilsonlearning.com

```
_http_outgoing.js:494 throw new TypeError('The header content contains invalid characters'); ^

15:14:14
TypeError: The header content contains invalid characters at validateHeader (_http_outgoing.js:494:11) at ClientRequest.setHeader (_http_outgoing.js:498:3) at new ClientRequest (_http_client.js:173:14) at Object.request (http.js:38:10) at Object.request (https.js:239:15) at /var/app/current/node_modules/simplecrawler/lib/crawler.js:1185:36 at FetchQueue.update (/var/app
TypeError: The header content contains invalid characters
at validateHeader (_http_outgoing.js:494:11)
at ClientRequest.setHeader (_http_outgoing.js:498:3)
at new ClientRequest (_http_client.js:173:14)
at Object.request (http.js:38:10)
at Object.request (https.js:239:15)
at /var/app/current/node_modules/simplecrawler/lib/crawler.js:1185:36
at FetchQueue.update (/var/app/current/node_modules/simplecrawler/lib/queue.js:229:9)
at Crawler.fetchQueueItem (/var/app/current/node_modules/simplecrawler/lib/crawler.js:1163:19)
at /var/app/current/node_modules/simplecrawler/lib/crawler.js:1794:25
at FetchQueue.oldestUnfetchedItem (/var/app/current/node_modules/simplecrawler/lib/queue.js:250:13)
at Crawler.crawl (/var/app/current/node_modules/simplecrawler/lib/crawler.js:1738:19)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by upugo-dev** [comment]
Appears as if this has been noted before #321 

Any update from @fredrikekelund @cgiffard ?

**Comment by kbychkov** [comment]
Hello @upugo-dev. I've examined your issue and think it isn't a problem with Simplecrawler. The same one is described [here](https://www.alexkras.com/typeerror-the-header-content-contains-invalid-characters/). In short, your site sends [incorrect headers](https://user-images.githubusercontent.com/23350930/54180200-14784200-44ac-11e9-90ec-9d0fa960ade7.png) therefore the Node.js `http` module throws the error.

These headers (cookies) are set by Google Analytics and I found the [question](https://stackoverflow.com/questions/8262477/google-analytics-illegal-cookie-breaks-python-backend) that addressed the similar problem. The main advice there is to upgrade GA tracking code. This is especially true because you're using very old `urchin.js` [tracking code](https://user-images.githubusercontent.com/23350930/54180294-50aba280-44ac-11e9-9ca7-1e7699bc9138.png) that was deprecated.

You can also set `crawler.acceptCookies = false` to prevent the cookies being sent by Simplecrawler and that should solve your problem.

**Comment by upugo-dev** [comment]
Hi kybchkov,

Thanks for the detailed response. Not my site, so not a lot I can do with it. We are using simplecrawler in a website analysis platform so in theory any website (of varying quality) can be thrown at it, so we need to ensure robustness against issues like this. 

Again, use of the urchin.js tracking code is outwith my control and we need to still be able to crawl sites with depreceated scripts like this. We may however be able to detect the use of these depreceated scripts and advise our users to update. 

The `crawler.acceptCookies = false` setting worked as quick-fix and I was able to crawl the site, so thank you for that.

**Comment by bogini** [comment]
`crawler.acceptCookies = false` also worked for me.

**Comment by upugo-dev** [comment]
so would it be possible to intercept the queueItem with a fetchCondition that validates the outgoing headers before the request is made? This would avoid crashing simplecrawler on encountering an invalid header, and additionally these queueItems could be returned in a `malformedRequests` object or similar. The current simplecrawler behaviour of failing fatally (granted, fairly noisily) doesn't seem to be an ideal scenario for developers!
