### ISSUE TITLE
SSL write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO

### ISSUE THREAD

**Issue by LeMoussel** [simplecrawler/simplecrawler#407]
Sometimes, getting the error below on some sites.

> write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:

This seems to be because wrong SSL version is being used (eg: _This server accepts RC4 cipher, but only with older protocols_, https://www.ssllabs.com/ssltest/analyze.html?d=www.dieboldnixdorf.com)

I found information that said to use secureProtocol 'SSLv3_method'  in the request.  But, I don't know SSL well, many people indicate that SSLv3 is dangerous/broken and obsolete  

Some idea on how can I crawl sites without this SSL error?

**Comment by fredrikekelund** [comment]
Are you receiving this error inside an event listener, or is the whole crawler process crashing?

**Comment by LeMoussel** [comment]
Receive this error inside an event listener (`robotstxterror` & `fetchclienterror` events)

**Comment by konstantinblaesi** [comment]
Which protocols do the proxy and the page you're trying to crawl use ? The crawler chooses between the http and https Node.js module or http(s) agents only depending on the queueItems protocol, see
* https://github.com/simplecrawler/simplecrawler/blob/master/lib/crawler.js#L1170
* https://github.com/simplecrawler/simplecrawler/blob/master/lib/crawler.js#L506

I assume crawling http with a http proxy or https with a https proxy would work. Everything else ? Sounds like trouble.

**Comment by LeMoussel** [comment]
Which protocols do the proxy : I don't know. I don't specify a protocol

I use crawler with this parameters 

- --proxyHostname "_@ip of proxy_"
- --proxyPort 3128

**Comment by konstantinblaesi** [comment]
The crawler always uses the http protocol for the proxy.
If you want you can try my branch, it has a little change regarding proxy handling in https://github.com/konstantinblaesi/node-simplecrawler/commit/9ebad813ccc3b05825afef1638ae59d1d8765f0b
It would be enough to delete node_modules/simplecrawler and run
```
npm install https://github.com/konstantinblaesi/node-simplecrawler#refactor-and-puppeteer
```

**Comment by LeMoussel** [comment]
@konstantinblaesi  same errors

**testSimpleCrawler.js**
```
const Crawler = require("simplecrawler");

let crawler = (new Crawler("https://www.probtp.com/"))
    .on("crawlstart", function(error) {
        console.log("crawlstart", Date());
    })
    .on("robotstxterror", function(error) {
        console.log("robotstxterror: ", error.message);
    })
    .on("fetch404", function (queueItem, responseBuffer) {
        console.log("fetch404: ", queueItem.url);
    })
    .on("fetcherror", function (queueItem, responseObject) {
        console.log("fetcherror: HTTP Status code %d %s", responseObject.statusCode, queueItem.url);
    })
    .on("fetchtimeout", function (queueItem, timeoutVal) {
        console.log("fetchtimeout: ", queueItem.url);
    })
    .on("fetchclienterror", function(queueItem, error) {
        console.log("fetchclienterror: %s %s", queueItem.url, error);
    })
    .on("complete", function() {
        console.log("complete ", Date());
    });

crawle.maxDepth = 1;
crawler.useProxy = true;
crawler.proxyHostname = "myproxy.test.fr";
crawler.proxyPort = 3128;

crawler.start()
```

**Results**

> crawlstart Wed Oct 04 2017 13:28:54 GMT+0200 (Paris, Madrid (heure d’été))
> robotstxterror:  write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:
> fetchclienterror: https://www.probtp.com/ Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:
>     at _errnoException (util.js:1041:11)
>     at WriteWrap.afterWrite [as oncomplete] (net.js:858:14)
> complete  Wed Oct 04 2017 13:28:54 GMT+0200 (Paris, Madrid (heure d’été))

**Remarks**
A) If I delete `node_modules/simplecrawler`, I got this error

> $ npm install https://github.com/konstantinblaesi/node-simplecrawler#refactor-and-puppeteer
> npm WARN checkPermissions Missing write access to C:\Users\LeMoussel\nodejs\crawlBot\node_modules\simplecrawler
> npm WARN crawlbot@1.0.0 No repository field.
> 
> npm ERR! path C:\Users\LeMoussel\nodejs\crawlBot\node_modules\simplecrawler
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall access
> npm ERR! enoent ENOENT: no such file or directory, access 'C:\Users\LeMoussel\nodejs\crawlBot\node_modules\simplecrawler'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent

I re-install `simplecrawler` & install your package => It's OK

B) When running I got this error

> Error: Cannot find module 'urijs'

I do

> $ npm install urijs
> npm WARN crawlbot@1.0.0 No repository field.
> 
> + urijs@1.19.0
> added 4 packages in 7.395s

**Comment by konstantinblaesi** [comment]
Seems to be some permission problem on your machine. Have you tried changing package.json to
```
"simplecrawler": "https://github.com/konstantinblaesi/node-simplecrawler#refactor-and-puppeteer",
```
, deleting node_modules and running `npm install` ?

**Comment by konstantinblaesi** [comment]
Must be a bug in my changes, I will investigate this.

**Comment by konstantinblaesi** [comment]
@LeMoussel Can you test again? I could not get my own proxy to work with the node module [tunnel](https://www.npmjs.com/package/tunnel) and switched to [proxy-agent](https://www.npmjs.com/package/proxy-agent) now. You should do a new install of my refactor-and-puppeteer branch, I made a fixup/rebase for the proxy commit https://github.com/konstantinblaesi/node-simplecrawler/commit/d14b21b0ec2d0562af42cd16ea528ee089edc220 .

**Comment by LeMoussel** [comment]
@konstantinblaesi  Installation OK & no errors 👍 

> => crawlstart Fri Oct 06 2017 08:53:15 GMT+0200 (Paris, Madrid (heure d’été))
> => fetcherror: HTTP Status code 403 https://www.probtp.com/probtp/web/salarie-node1_5419.html
> => complete  Fri Oct 06 2017 08:53:17 GMT+0200 (Paris, Madrid (heure d’été))

**Rem:** For 403, I think the site checks the UA.

However I note a strange behavior. For some sites, after `complete`event, program doesn't exit
For example with this site http://f4b1.com/

> => crawlstart Fri Oct 06 2017 09:02:54 GMT+0200 (Paris, Madrid (heure d’été))
> => complete  Fri Oct 06 2017 09:02:55 GMT+0200 (Paris, Madrid (heure d’été))
> Program doesn't exit, in an infinite loop?

**Comment by LeMoussel** [comment]
@konstantinblaesi will it be integrated in simplecrawlers master branch?

**Comment by LeMoussel** [comment]
@konstantinblaesi I am interested in using puppeteer as a fetch client. I have questions / comments. How can I ask? Should I use this issue  [Basic and X509 Auth, Proxy fixes and Puppeteer support for client side generated content](https://github.com/simplecrawler/simplecrawler/pull/402)?

**Comment by konstantinblaesi** [comment]
@LeMoussel Yes, I think it would make sense to ask in #402 .
